In [6]:
import numpy as np
A=np.array([[2,-1,0,0,0],
            [-1,2,-1,0,0],
            [0,-1,2,-1,0],
            [0,0,-1,2,-1],
            [0,0,0,-1,2]])

R=np.array([[1,2,1,0,0],
            [0,0,1,2,1]])
P = R.T

RA = R@A
RA

array([[ 0,  2,  0, -1,  0],
       [ 0, -1,  0,  2,  0]])

In [8]:
A2 = RA@P
A2

array([[ 4, -2],
       [-2,  4]])

In [12]:
A2_inv = np.linalg.inv(A2)
A2_inv

6*A2_inv

array([[2., 1.],
       [1., 2.]])

In [18]:
6*A2_inv@RA

array([[0., 3., 0., 0., 0.],
       [0., 0., 0., 3., 0.]])

In [20]:
S=P@A2_inv@RA
S

array([[0. , 0.5, 0. , 0. , 0. ],
       [0. , 1. , 0. , 0. , 0. ],
       [0. , 0.5, 0. , 0.5, 0. ],
       [0. , 0. , 0. , 1. , 0. ],
       [0. , 0. , 0. , 0.5, 0. ]])

In [22]:
np.linalg.eig(S)

EigResult(eigenvalues=array([0., 0., 0., 1., 1.]), eigenvectors=array([[0.        , 0.        , 1.        , 0.40824829, 0.        ],
       [0.        , 0.        , 0.        , 0.81649658, 0.        ],
       [1.        , 0.        , 0.        , 0.40824829, 0.40824829],
       [0.        , 0.        , 0.        , 0.        , 0.81649658],
       [0.        , 1.        , 0.        , 0.        , 0.40824829]]))

In [23]:
# spectral radius of I-S
np.max(np.abs(np.linalg.eig(np.eye(5)-S)[0]))

1.0

In [33]:
# weighted Jacobi
I = np.identity(5)
M = I - 1/3 * A
M

array([[0.33333333, 0.33333333, 0.        , 0.        , 0.        ],
       [0.33333333, 0.33333333, 0.33333333, 0.        , 0.        ],
       [0.        , 0.33333333, 0.33333333, 0.33333333, 0.        ],
       [0.        , 0.        , 0.33333333, 0.33333333, 0.33333333],
       [0.        , 0.        , 0.        , 0.33333333, 0.33333333]])

In [35]:
np.linalg.eig(M@(np.eye(5)-S)@M)[0]

array([ 0.00000000e+00,  1.11111111e-01, -1.04083409e-17,  1.11111111e-01,
        1.11111111e-01])

In [37]:
np.linalg.eig(M)[0]

array([-2.44016936e-01,  9.10683603e-01,  6.66666667e-01,  3.33333333e-01,
        8.86986401e-17])

In [39]:
I-S

array([[ 1. , -0.5,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. , -0.5,  1. , -0.5,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , -0.5,  1. ]])

In [49]:
from sympy import symbols, cos, sin, pi
k = symbols('k')
N = symbols('N')
yk = [sin(pi*k/N), sin(2*pi*k/N), sin(3*pi*k/N), sin(4*pi*k/N), sin(5*pi*k/N)]
yk


[sin(pi*k/N), sin(2*pi*k/N), sin(3*pi*k/N), sin(4*pi*k/N), sin(5*pi*k/N)]

In [46]:
%pip install sympy

Note: you may need to restart the kernel to use updated packages.


In [54]:
(I-S) @ yk


array([1.0*sin(pi*k/N) - 0.5*sin(2*pi*k/N), 0,
       -0.5*sin(2*pi*k/N) + 1.0*sin(3*pi*k/N) - 0.5*sin(4*pi*k/N), 0,
       -0.5*sin(4*pi*k/N) + 1.0*sin(5*pi*k/N)], dtype=object)

In [79]:
import pprint
from sympy import init_printing
init_printing()

ISy = (I-S) @ yk
for i in ISy:
    print(i)


1.0*sin(pi*k/N) - 0.5*sin(2*pi*k/N)
0
-0.5*sin(2*pi*k/N) + 1.0*sin(3*pi*k/N) - 0.5*sin(4*pi*k/N)
0
-0.5*sin(4*pi*k/N) + 1.0*sin(5*pi*k/N)


In [62]:
Yk = [sin(pi*(N-k)/N), sin(2*pi*(N-k)/N), sin(3*pi*(N-k)/N), sin(4*pi*(N-k)/N), sin(5*pi*(N-k)/N)]
Yk

In [80]:
ISY = (I-S) @ Yk
for i in ISY:
    print(i)

1.0*sin(pi*(N - k)/N) - 0.5*sin(2*pi*(N - k)/N)
0
-0.5*sin(2*pi*(N - k)/N) + 1.0*sin(3*pi*(N - k)/N) - 0.5*sin(4*pi*(N - k)/N)
0
-0.5*sin(4*pi*(N - k)/N) + 1.0*sin(5*pi*(N - k)/N)


In [82]:
ISY + ISy

array([1.0*sin(pi*k/N) - 0.5*sin(2*pi*k/N) + 1.0*sin(pi*(N - k)/N) - 0.5*sin(2*pi*(N - k)/N),
       0,
       -0.5*sin(2*pi*k/N) + 1.0*sin(3*pi*k/N) - 0.5*sin(4*pi*k/N) - 0.5*sin(2*pi*(N - k)/N) + 1.0*sin(3*pi*(N - k)/N) - 0.5*sin(4*pi*(N - k)/N),
       0,
       -0.5*sin(4*pi*k/N) + 1.0*sin(5*pi*k/N) - 0.5*sin(4*pi*(N - k)/N) + 1.0*sin(5*pi*(N - k)/N)],
      dtype=object)

In [86]:
for i in ISY + ISy:
    print(i)

1.0*sin(pi*k/N) - 0.5*sin(2*pi*k/N) + 1.0*sin(pi*(N - k)/N) - 0.5*sin(2*pi*(N - k)/N)
0
-0.5*sin(2*pi*k/N) + 1.0*sin(3*pi*k/N) - 0.5*sin(4*pi*k/N) - 0.5*sin(2*pi*(N - k)/N) + 1.0*sin(3*pi*(N - k)/N) - 0.5*sin(4*pi*(N - k)/N)
0
-0.5*sin(4*pi*k/N) + 1.0*sin(5*pi*k/N) - 0.5*sin(4*pi*(N - k)/N) + 1.0*sin(5*pi*(N - k)/N)


In [97]:
A = np.array([[2,-1,0,0,-1],
            [-1,2,-1,0,0],
            [0,-1,2,-1,0],
            [0,0,-1,2,-1],
            [-1,0,0,-1,2]])
np.linalg.eigvals(A)

array([ 3.61803399e+00,  1.38196601e+00, -2.38411352e-16,  3.61803399e+00,
        1.38196601e+00])

In [100]:
np.linalg.eig(A)[1]

array([[-0.63245553,  0.63245553, -0.4472136 , -0.06553916,  0.09723954],
       [ 0.51166727,  0.19543951, -0.4472136 , -0.31672435, -0.56430038],
       [-0.19543951, -0.51166727, -0.4472136 ,  0.57800993, -0.44599636],
       [-0.19543951, -0.51166727, -0.4472136 , -0.61851536,  0.28865947],
       [ 0.51166727,  0.19543951, -0.4472136 ,  0.42276894,  0.62439772]])

\begin{pmatrix}
 2 & -1 & 0  & 0 & 0 \\
 -1 & 2 & -1 & 0 & 0 \\
 0 & -1 & 2 & -1 & 0 \\
 0 & 0 & -1 & 2 & -1 \\
 0 & 0 & 0 & -1 & 2 \\
\end{pmatrix}