In [25]:
#small_example_show_TG_spectral_radius
import numpy as np
import scipy
A = np.array([[2,-1,0,0],
              [-1,2,-1,0],
              [0,-1,2,-1],
              [0,0,-1,2]])
P = np.array([  [1,     0],
                [0.5, 0.5],
                [0,     1],
                [0,   0.5]])
print('A = \n', A)
print('P = \n', P)

A = 
 [[ 2 -1  0  0]
 [-1  2 -1  0]
 [ 0 -1  2 -1]
 [ 0  0 -1  2]]
P = 
 [[1.  0. ]
 [0.5 0.5]
 [0.  1. ]
 [0.  0.5]]


In [26]:
R = P.T
Ac = R @ A @ P
print('Ac = \n', Ac)

Ac_inv = np.linalg.inv(Ac)
print('Ac_inv = \n', Ac_inv)

S = P@ Ac_inv @ R @ A
print('S = \n', S)

TG = np.eye(4) - S
print('TG = \n', TG)

eigvals = np.linalg.eigvals(TG)
print('eigvals = ', eigvals)

Ac = 
 [[ 1.5 -0.5]
 [-0.5  1. ]]
Ac_inv = 
 [[0.8 0.4]
 [0.4 1.2]]
S = 
 [[ 1.00000000e+00  5.55111512e-17 -2.77555756e-17  0.00000000e+00]
 [ 5.00000000e-01  0.00000000e+00  5.00000000e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  5.00000000e-01  0.00000000e+00]]
TG = 
 [[ 1.11022302e-16 -5.55111512e-17  2.77555756e-17  0.00000000e+00]
 [-5.00000000e-01  1.00000000e+00 -5.00000000e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -5.00000000e-01  1.00000000e+00]]
eigvals =  [0. 1. 1. 0.]


In [27]:
# Now Add the weighted Jacobi smoother
omega = 2./3.
D_inv = np.diag(1./np.diag(A))
M = np.eye(4)-omega*D_inv@A
print('M = \n', M)

M = 
 [[0.33333333 0.33333333 0.         0.        ]
 [0.33333333 0.33333333 0.33333333 0.        ]
 [0.         0.33333333 0.33333333 0.33333333]
 [0.         0.         0.33333333 0.33333333]]


In [37]:
M_TG_M = M @ TG @ M
# print('M_TG_M = \n', M_TG_M)
eig = np.linalg.eigvals(M_TG_M)
# list(map('{:.1f}'.format,eig))
# eig = np.round(eig, 2)
print(f'eigvals of M_TG_M = \n {eig}')

eigvals of M_TG_M = 
 [-1.73472348e-17+7.94392798e-18j -1.73472348e-17-7.94392798e-18j
  1.11111111e-01+0.00000000e+00j  1.11111111e-01+0.00000000e+00j]


In [40]:
eig_M = np.linalg.eigvals(M@M)
print("eig M@M\n",eig_M)

eig M@M
 [0.76156689 0.29089267 0.01621089 0.04244067]
