In [99]:
import numpy as np


In [103]:
A = np.array([[1,0,0,-1],[0,1,0,-1],[0,0,1,-1]])
B = np.random.rand(3,3)
A

array([[ 1,  0,  0, -1],
       [ 0,  1,  0, -1],
       [ 0,  0,  1, -1]])

In [104]:
A.T@A

array([[ 1,  0,  0, -1],
       [ 0,  1,  0, -1],
       [ 0,  0,  1, -1],
       [-1, -1, -1,  3]])

In [106]:
A.T@B@A

array([[ 0.81106084,  0.4301976 ,  0.90435471, -2.14561316],
       [ 0.34649926,  0.37355602,  0.60969486, -1.32975015],
       [ 0.04149326,  0.85780947,  0.76576123, -1.66506397],
       [-1.19905336, -1.6615631 , -2.2798108 ,  5.14042727]])

In [113]:
C=A.T@B@A
np.sum(C[1,:])

0.0

In [114]:
0.81106084+  0.4301976 +  0.90435471+ -2.14561316

-9.99999993922529e-09